
FilterGPS:
  # Kalman filter parameters
  P: [0.0001, 0.0001, 0.25, 0.0001]
  Q: [0.0, 0.0, 0.001, 0.0001]
  V: [0.1, 0.1, 0.1]
  predict_hz: 10.0
  update_hz: 10.0
  seed: 60
  # Parameters for circle distortion
  embedding_fn_name: modelC
  frame_id: world
  hover_height: 1.0  # meters
  radius_nominal: 1.0  # meters
  omega_nominal: 0.8   # radians per second
  k_phi: 0.3

FilterRelative:
  # Kalman filter parameters
  P_ego: [0.0001, 0.0001, 0.25, 0.0001]
  Q_ego: [0.0, 0.0, 0.001, 0.0001]
  V_ego: [0.1, 0.1, 0.1]
  P_rel: [0.0001, 0.0001, 0.25]
  Q_rel: [0.0, 0.0, 0.01]
  V_rel: [0.1, 0.1, 0.1]
  predict_hz: 10.0
  update_hz: 10.0
  seed: 60
  # Parameters for circle distortion
  embedding_fn_name: modelC
  frame_id: world
  hover_height: 1.0    # meters
  radius_nominal: 1.0  # meters
  omega_nominal: 0.2   # radians per second
  k_phi: 0.3