FilterRelative:
  # Kalman filter parameters
  P_ego: [0.0001, 0.0001, 0.25, 0.15]
  Q_ego: [0.0, 0.0, 0.0001, 0.0]
  V_ego: [0.1, 0.1, 0.1]
  P_rel: [0.0001, 0.0001, 0.25]
  Q_rel: [0.0, 0.0, 0.001]
  V_rel: [0.1, 0.1, 0.1]
  predict_hz: 100.0
  update_hz: 100.0
  seed: 60
  # Parameters for circle distortion
  embedding_fn_name: modelE
  frame_id: world
  hover_height: 0.3 # meters
  radius_nominal: 0.5 # meters
  omega_nominal: 0.6  # radians per second
  k_phi: 0.2

FilterUnicycle:
  # Kalman filter parameters
  # [x, y, theta, omega, v, z_ground]
  P: [1.0, 1.0, 0.15, 0.5, 0.2, 0.1]
  Q: [0.01, 0.01, 0.01, 0.1, 0.05, 0.000001]
  V: [0.02, 0.02, 0.02]
  predict_hz: 100.0
  update_hz: 10.0
  seed: 60
  # Other parameters
  frame_id: world
  hover_height: 0.3  # meters
  zupt_threshold: 0.00001 # m/s
  k_phi: 1.0

FollowLimoEncirclementFilterUnicycle:
  whoisthetarget: limo
  # Kalman filter parameters for tracking the limo robot
  target_limo:
    # [x, y, theta, omega, v, z_ground]
    P: [1.0, 1.0, 0.15, 0.5, 0.2, 0.01]
    Q: [0.01, 0.01, 0.05, 0.1, 0.1, 0.01]
    V: [0.02, 0.02, 0.02]
  target_drone:
    # [x, y, theta, omega, v, z_ground]
    P: [1.0, 1.0, 0.15, 0.5, 0.2, 0.1]
    Q: [0.01, 0.01, 0.05, 0.1, 0.1, 0.2]
    V: [0.02, 0.02, 0.02]
  # Kalman filter parameters for relative filter used by the drones
  relative:
    P_rel: [0.1, 0.1]      # rad, rad
    Q_rel: [0.07, 0.07]    # rad/s, rad/s
    V_rel: [0.01, 0.01]    # rad, rad
    Noise_relative: [0.02, 0.02, 0.02]  # m, m, m (x, y, z)
  # Other parameters
  controls:
    radius_nominal: 1.0      # meters
    omega_nominal: 1.0        # radians per second
    hover_height: 0.5        # meters
    encirclement_height: 0.5  # meters
    zupt_threshold: 0.005     # m/s
    k_phi: 1.0              # phase controller gain
    k_r: 15.0                 # radius controller gain
    k_omega: 1.1             # desired omega velocity controller gain
  flocking:
    k_v: 0.35                  # Flocking gain
    safe_distance_gain: 1.5   # Gain to be used with the nominal radius
  others:
    predict_hz: 100.0
    update_hz: 10.0
    seed: 10
    frame_id: world  
